#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanLapTop.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
    using System.Configuration;
    using System;
   


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebBanLapTop")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
        public DatabaseDataContext() :
    base(System.Configuration.ConfigurationManager.ConnectionStrings["WebBanLapTopConnectionString"].ConnectionString, mappingSource)
        {
        }


        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_product_image(tb_product_image instance);
    partial void Updatetb_product_image(tb_product_image instance);
    partial void Deletetb_product_image(tb_product_image instance);
    partial void Inserttb_order_detail(tb_order_detail instance);
    partial void Updatetb_order_detail(tb_order_detail instance);
    partial void Deletetb_order_detail(tb_order_detail instance);
    partial void Inserttb_payment(tb_payment instance);
    partial void Updatetb_payment(tb_payment instance);
    partial void Deletetb_payment(tb_payment instance);
    partial void Inserttb_product(tb_product instance);
    partial void Updatetb_product(tb_product instance);
    partial void Deletetb_product(tb_product instance);
    partial void Inserttb_product_discount(tb_product_discount instance);
    partial void Updatetb_product_discount(tb_product_discount instance);
    partial void Deletetb_product_discount(tb_product_discount instance);
    partial void Inserttb_order(tb_order instance);
    partial void Updatetb_order(tb_order instance);
    partial void Deletetb_order(tb_order instance);
    partial void Inserttb_cart_item(tb_cart_item instance);
    partial void Updatetb_cart_item(tb_cart_item instance);
    partial void Deletetb_cart_item(tb_cart_item instance);
    partial void Inserttb_cart(tb_cart instance);
    partial void Updatetb_cart(tb_cart instance);
    partial void Deletetb_cart(tb_cart instance);
    partial void Inserttb_brand(tb_brand instance);
    partial void Updatetb_brand(tb_brand instance);
    partial void Deletetb_brand(tb_brand instance);
    partial void Inserttb_user(tb_user instance);
    partial void Updatetb_user(tb_user instance);
    partial void Deletetb_user(tb_user instance);
    partial void Inserttb_shipping(tb_shipping instance);
    partial void Updatetb_shipping(tb_shipping instance);
    partial void Deletetb_shipping(tb_shipping instance);
    partial void Inserttb_review(tb_review instance);
    partial void Updatetb_review(tb_review instance);
    partial void Deletetb_review(tb_review instance);
    #endregion
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_product_image> tb_product_images
		{
			get
			{
				return this.GetTable<tb_product_image>();
			}
		}
		
		public System.Data.Linq.Table<tb_order_detail> tb_order_details
		{
			get
			{
				return this.GetTable<tb_order_detail>();
			}
		}
		
		public System.Data.Linq.Table<tb_payment> tb_payments
		{
			get
			{
				return this.GetTable<tb_payment>();
			}
		}
		
		public System.Data.Linq.Table<tb_product> tb_products
		{
			get
			{
				return this.GetTable<tb_product>();
			}
		}
		
		public System.Data.Linq.Table<tb_product_discount> tb_product_discounts
		{
			get
			{
				return this.GetTable<tb_product_discount>();
			}
		}
		
		public System.Data.Linq.Table<tb_order> tb_orders
		{
			get
			{
				return this.GetTable<tb_order>();
			}
		}
		
		public System.Data.Linq.Table<tb_cart_item> tb_cart_items
		{
			get
			{
				return this.GetTable<tb_cart_item>();
			}
		}
		
		public System.Data.Linq.Table<tb_cart> tb_carts
		{
			get
			{
				return this.GetTable<tb_cart>();
			}
		}
		
		public System.Data.Linq.Table<tb_brand> tb_brands
		{
			get
			{
				return this.GetTable<tb_brand>();
			}
		}
		
		public System.Data.Linq.Table<tb_user> tb_users
		{
			get
			{
				return this.GetTable<tb_user>();
			}
		}
		
		public System.Data.Linq.Table<tb_shipping> tb_shippings
		{
			get
			{
				return this.GetTable<tb_shipping>();
			}
		}
		
		public System.Data.Linq.Table<tb_review> tb_reviews
		{
			get
			{
				return this.GetTable<tb_review>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_product_image")]
	public partial class tb_product_image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _product_image_id;
		
		private System.Nullable<int> _product_id;
		
		private string _image;
		
		private EntityRef<tb_product> _tb_product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_image_idChanging(int value);
    partial void Onproduct_image_idChanged();
    partial void Onproduct_idChanging(System.Nullable<int> value);
    partial void Onproduct_idChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    #endregion
		
		public tb_product_image()
		{
			this._tb_product = default(EntityRef<tb_product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_image_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int product_image_id
		{
			get
			{
				return this._product_image_id;
			}
			set
			{
				if ((this._product_image_id != value))
				{
					this.Onproduct_image_idChanging(value);
					this.SendPropertyChanging();
					this._product_image_id = value;
					this.SendPropertyChanged("product_image_id");
					this.Onproduct_image_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int")]
		public System.Nullable<int> product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._tb_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_product_image", Storage="_tb_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
		public tb_product tb_product
		{
			get
			{
				return this._tb_product.Entity;
			}
			set
			{
				tb_product previousValue = this._tb_product.Entity;
				if (((previousValue != value) 
							|| (this._tb_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_product.Entity = null;
						previousValue.tb_product_images.Remove(this);
					}
					this._tb_product.Entity = value;
					if ((value != null))
					{
						value.tb_product_images.Add(this);
						this._product_id = value.product_id;
					}
					else
					{
						this._product_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_order_detail")]
	public partial class tb_order_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _orderdetail_id;
		
		private System.Nullable<int> _order_id;
		
		private System.Nullable<int> _product_id;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<decimal> _price;
		
		private EntityRef<tb_product> _tb_product;
		
		private EntityRef<tb_order> _tb_order;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorderdetail_idChanging(int value);
    partial void Onorderdetail_idChanged();
    partial void Onorder_idChanging(System.Nullable<int> value);
    partial void Onorder_idChanged();
    partial void Onproduct_idChanging(System.Nullable<int> value);
    partial void Onproduct_idChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    #endregion
		
		public tb_order_detail()
		{
			this._tb_product = default(EntityRef<tb_product>);
			this._tb_order = default(EntityRef<tb_order>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderdetail_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int orderdetail_id
		{
			get
			{
				return this._orderdetail_id;
			}
			set
			{
				if ((this._orderdetail_id != value))
				{
					this.Onorderdetail_idChanging(value);
					this.SendPropertyChanging();
					this._orderdetail_id = value;
					this.SendPropertyChanged("orderdetail_id");
					this.Onorderdetail_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int")]
		public System.Nullable<int> order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					if (this._tb_order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int")]
		public System.Nullable<int> product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._tb_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_order_detail", Storage="_tb_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
		public tb_product tb_product
		{
			get
			{
				return this._tb_product.Entity;
			}
			set
			{
				tb_product previousValue = this._tb_product.Entity;
				if (((previousValue != value) 
							|| (this._tb_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_product.Entity = null;
						previousValue.tb_order_details.Remove(this);
					}
					this._tb_product.Entity = value;
					if ((value != null))
					{
						value.tb_order_details.Add(this);
						this._product_id = value.product_id;
					}
					else
					{
						this._product_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_product");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_order_tb_order_detail", Storage="_tb_order", ThisKey="order_id", OtherKey="order_id", IsForeignKey=true)]
		public tb_order tb_order
		{
			get
			{
				return this._tb_order.Entity;
			}
			set
			{
				tb_order previousValue = this._tb_order.Entity;
				if (((previousValue != value) 
							|| (this._tb_order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_order.Entity = null;
						previousValue.tb_order_details.Remove(this);
					}
					this._tb_order.Entity = value;
					if ((value != null))
					{
						value.tb_order_details.Add(this);
						this._order_id = value.order_id;
					}
					else
					{
						this._order_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_order");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_payment")]
	public partial class tb_payment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _payment_id;
		
		private string _method;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _payment_date;
		
		private EntitySet<tb_order> _tb_orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpayment_idChanging(int value);
    partial void Onpayment_idChanged();
    partial void OnmethodChanging(string value);
    partial void OnmethodChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onpayment_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onpayment_dateChanged();
    #endregion
		
		public tb_payment()
		{
			this._tb_orders = new EntitySet<tb_order>(new Action<tb_order>(this.attach_tb_orders), new Action<tb_order>(this.detach_tb_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int payment_id
		{
			get
			{
				return this._payment_id;
			}
			set
			{
				if ((this._payment_id != value))
				{
					this.Onpayment_idChanging(value);
					this.SendPropertyChanging();
					this._payment_id = value;
					this.SendPropertyChanged("payment_id");
					this.Onpayment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_method", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string method
		{
			get
			{
				return this._method;
			}
			set
			{
				if ((this._method != value))
				{
					this.OnmethodChanging(value);
					this.SendPropertyChanging();
					this._method = value;
					this.SendPropertyChanged("method");
					this.OnmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> payment_date
		{
			get
			{
				return this._payment_date;
			}
			set
			{
				if ((this._payment_date != value))
				{
					this.Onpayment_dateChanging(value);
					this.SendPropertyChanging();
					this._payment_date = value;
					this.SendPropertyChanged("payment_date");
					this.Onpayment_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_payment_tb_order", Storage="_tb_orders", ThisKey="payment_id", OtherKey="payment_id")]
		public EntitySet<tb_order> tb_orders
		{
			get
			{
				return this._tb_orders;
			}
			set
			{
				this._tb_orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_orders(tb_order entity)
		{
			this.SendPropertyChanging();
			entity.tb_payment = this;
		}
		
		private void detach_tb_orders(tb_order entity)
		{
			this.SendPropertyChanging();
			entity.tb_payment = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_product")]
	public partial class tb_product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _product_id;
		
		private System.Nullable<int> _category_id;
		
		private System.Nullable<int> _brand_id;
		
		private string _name;
		
		private string _description;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<decimal> _price;
		
		private string _image;
		
		private System.Nullable<bool> _is_featured;
		
		private System.Nullable<bool> _is_new;
		
		private System.Nullable<System.DateTime> _create_at;
		
		private EntitySet<tb_product_image> _tb_product_images;
		
		private EntitySet<tb_order_detail> _tb_order_details;
		
		private EntitySet<tb_product_discount> _tb_product_discounts;
		
		private EntitySet<tb_cart_item> _tb_cart_items;
		
		private EntitySet<tb_review> _tb_reviews;
		
		private EntityRef<tb_brand> _tb_brand;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    partial void Oncategory_idChanging(System.Nullable<int> value);
    partial void Oncategory_idChanged();
    partial void Onbrand_idChanging(System.Nullable<int> value);
    partial void Onbrand_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void Onis_featuredChanging(System.Nullable<bool> value);
    partial void Onis_featuredChanged();
    partial void Onis_newChanging(System.Nullable<bool> value);
    partial void Onis_newChanged();
    partial void Oncreate_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_atChanged();
    #endregion
		
		public tb_product()
		{
			this._tb_product_images = new EntitySet<tb_product_image>(new Action<tb_product_image>(this.attach_tb_product_images), new Action<tb_product_image>(this.detach_tb_product_images));
			this._tb_order_details = new EntitySet<tb_order_detail>(new Action<tb_order_detail>(this.attach_tb_order_details), new Action<tb_order_detail>(this.detach_tb_order_details));
			this._tb_product_discounts = new EntitySet<tb_product_discount>(new Action<tb_product_discount>(this.attach_tb_product_discounts), new Action<tb_product_discount>(this.detach_tb_product_discounts));
			this._tb_cart_items = new EntitySet<tb_cart_item>(new Action<tb_cart_item>(this.attach_tb_cart_items), new Action<tb_cart_item>(this.detach_tb_cart_items));
			this._tb_reviews = new EntitySet<tb_review>(new Action<tb_review>(this.attach_tb_reviews), new Action<tb_review>(this.detach_tb_reviews));
			this._tb_brand = default(EntityRef<tb_brand>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int")]
		public System.Nullable<int> category_id
		{
			get
			{
				return this._category_id;
			}
			set
			{
				if ((this._category_id != value))
				{
					this.Oncategory_idChanging(value);
					this.SendPropertyChanging();
					this._category_id = value;
					this.SendPropertyChanged("category_id");
					this.Oncategory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_id", DbType="Int")]
		public System.Nullable<int> brand_id
		{
			get
			{
				return this._brand_id;
			}
			set
			{
				if ((this._brand_id != value))
				{
					if (this._tb_brand.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbrand_idChanging(value);
					this.SendPropertyChanging();
					this._brand_id = value;
					this.SendPropertyChanged("brand_id");
					this.Onbrand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_featured", DbType="Bit")]
		public System.Nullable<bool> is_featured
		{
			get
			{
				return this._is_featured;
			}
			set
			{
				if ((this._is_featured != value))
				{
					this.Onis_featuredChanging(value);
					this.SendPropertyChanging();
					this._is_featured = value;
					this.SendPropertyChanged("is_featured");
					this.Onis_featuredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_new", DbType="Bit")]
		public System.Nullable<bool> is_new
		{
			get
			{
				return this._is_new;
			}
			set
			{
				if ((this._is_new != value))
				{
					this.Onis_newChanging(value);
					this.SendPropertyChanging();
					this._is_new = value;
					this.SendPropertyChanged("is_new");
					this.Onis_newChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_at
		{
			get
			{
				return this._create_at;
			}
			set
			{
				if ((this._create_at != value))
				{
					this.Oncreate_atChanging(value);
					this.SendPropertyChanging();
					this._create_at = value;
					this.SendPropertyChanged("create_at");
					this.Oncreate_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_product_image", Storage="_tb_product_images", ThisKey="product_id", OtherKey="product_id")]
		public EntitySet<tb_product_image> tb_product_images
		{
			get
			{
				return this._tb_product_images;
			}
			set
			{
				this._tb_product_images.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_order_detail", Storage="_tb_order_details", ThisKey="product_id", OtherKey="product_id")]
		public EntitySet<tb_order_detail> tb_order_details
		{
			get
			{
				return this._tb_order_details;
			}
			set
			{
				this._tb_order_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_product_discount", Storage="_tb_product_discounts", ThisKey="product_id", OtherKey="product_id")]
		public EntitySet<tb_product_discount> tb_product_discounts
		{
			get
			{
				return this._tb_product_discounts;
			}
			set
			{
				this._tb_product_discounts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_cart_item", Storage="_tb_cart_items", ThisKey="product_id", OtherKey="product_id")]
		public EntitySet<tb_cart_item> tb_cart_items
		{
			get
			{
				return this._tb_cart_items;
			}
			set
			{
				this._tb_cart_items.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_review", Storage="_tb_reviews", ThisKey="product_id", OtherKey="product_id")]
		public EntitySet<tb_review> tb_reviews
		{
			get
			{
				return this._tb_reviews;
			}
			set
			{
				this._tb_reviews.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_brand_tb_product", Storage="_tb_brand", ThisKey="brand_id", OtherKey="brand_id", IsForeignKey=true)]
		public tb_brand tb_brand
		{
			get
			{
				return this._tb_brand.Entity;
			}
			set
			{
				tb_brand previousValue = this._tb_brand.Entity;
				if (((previousValue != value) 
							|| (this._tb_brand.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_brand.Entity = null;
						previousValue.tb_products.Remove(this);
					}
					this._tb_brand.Entity = value;
					if ((value != null))
					{
						value.tb_products.Add(this);
						this._brand_id = value.brand_id;
					}
					else
					{
						this._brand_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_brand");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_product_images(tb_product_image entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = this;
		}
		
		private void detach_tb_product_images(tb_product_image entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = null;
		}
		
		private void attach_tb_order_details(tb_order_detail entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = this;
		}
		
		private void detach_tb_order_details(tb_order_detail entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = null;
		}
		
		private void attach_tb_product_discounts(tb_product_discount entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = this;
		}
		
		private void detach_tb_product_discounts(tb_product_discount entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = null;
		}
		
		private void attach_tb_cart_items(tb_cart_item entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = this;
		}
		
		private void detach_tb_cart_items(tb_cart_item entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = null;
		}
		
		private void attach_tb_reviews(tb_review entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = this;
		}
		
		private void detach_tb_reviews(tb_review entity)
		{
			this.SendPropertyChanging();
			entity.tb_product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_product_discount")]
	public partial class tb_product_discount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _product_discount_id;
		
		private string _name;
		
		private System.Nullable<decimal> _amount;
		
		private System.Nullable<bool> _is_fixed;
		
		private System.Nullable<System.DateTime> _start_date;
		
		private System.Nullable<System.DateTime> _end_date;
		
		private System.Nullable<int> _product_id;
		
		private EntityRef<tb_product> _tb_product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_discount_idChanging(int value);
    partial void Onproduct_discount_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnamountChanging(System.Nullable<decimal> value);
    partial void OnamountChanged();
    partial void Onis_fixedChanging(System.Nullable<bool> value);
    partial void Onis_fixedChanged();
    partial void Onstart_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onend_dateChanged();
    partial void Onproduct_idChanging(System.Nullable<int> value);
    partial void Onproduct_idChanged();
    #endregion
		
		public tb_product_discount()
		{
			this._tb_product = default(EntityRef<tb_product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_discount_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int product_discount_id
		{
			get
			{
				return this._product_discount_id;
			}
			set
			{
				if ((this._product_discount_id != value))
				{
					this.Onproduct_discount_idChanging(value);
					this.SendPropertyChanging();
					this._product_discount_id = value;
					this.SendPropertyChanged("product_discount_id");
					this.Onproduct_discount_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_fixed", DbType="Bit")]
		public System.Nullable<bool> is_fixed
		{
			get
			{
				return this._is_fixed;
			}
			set
			{
				if ((this._is_fixed != value))
				{
					this.Onis_fixedChanging(value);
					this.SendPropertyChanging();
					this._is_fixed = value;
					this.SendPropertyChanged("is_fixed");
					this.Onis_fixedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this.Onstart_dateChanging(value);
					this.SendPropertyChanging();
					this._start_date = value;
					this.SendPropertyChanged("start_date");
					this.Onstart_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int")]
		public System.Nullable<int> product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._tb_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_product_discount", Storage="_tb_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
		public tb_product tb_product
		{
			get
			{
				return this._tb_product.Entity;
			}
			set
			{
				tb_product previousValue = this._tb_product.Entity;
				if (((previousValue != value) 
							|| (this._tb_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_product.Entity = null;
						previousValue.tb_product_discounts.Remove(this);
					}
					this._tb_product.Entity = value;
					if ((value != null))
					{
						value.tb_product_discounts.Add(this);
						this._product_id = value.product_id;
					}
					else
					{
						this._product_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_order")]
	public partial class tb_order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_id;
		
		private System.Nullable<int> _user_id;
		
		private System.Nullable<decimal> _total_mount;
		
		private System.Nullable<System.DateTime> _order_date;
		
		private string _status;
		
		private System.Nullable<int> _payment_id;
		
		private System.Nullable<int> _shipping_id;
		
		private EntitySet<tb_order_detail> _tb_order_details;
		
		private EntityRef<tb_payment> _tb_payment;
		
		private EntityRef<tb_user> _tb_user;
		
		private EntityRef<tb_shipping> _tb_shipping;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Ontotal_mountChanging(System.Nullable<decimal> value);
    partial void Ontotal_mountChanged();
    partial void Onorder_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onorder_dateChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onpayment_idChanging(System.Nullable<int> value);
    partial void Onpayment_idChanged();
    partial void Onshipping_idChanging(System.Nullable<int> value);
    partial void Onshipping_idChanged();
    #endregion
		
		public tb_order()
		{
			this._tb_order_details = new EntitySet<tb_order_detail>(new Action<tb_order_detail>(this.attach_tb_order_details), new Action<tb_order_detail>(this.detach_tb_order_details));
			this._tb_payment = default(EntityRef<tb_payment>);
			this._tb_user = default(EntityRef<tb_user>);
			this._tb_shipping = default(EntityRef<tb_shipping>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._tb_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_mount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> total_mount
		{
			get
			{
				return this._total_mount;
			}
			set
			{
				if ((this._total_mount != value))
				{
					this.Ontotal_mountChanging(value);
					this.SendPropertyChanging();
					this._total_mount = value;
					this.SendPropertyChanged("total_mount");
					this.Ontotal_mountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> order_date
		{
			get
			{
				return this._order_date;
			}
			set
			{
				if ((this._order_date != value))
				{
					this.Onorder_dateChanging(value);
					this.SendPropertyChanging();
					this._order_date = value;
					this.SendPropertyChanged("order_date");
					this.Onorder_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_id", DbType="Int")]
		public System.Nullable<int> payment_id
		{
			get
			{
				return this._payment_id;
			}
			set
			{
				if ((this._payment_id != value))
				{
					if (this._tb_payment.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpayment_idChanging(value);
					this.SendPropertyChanging();
					this._payment_id = value;
					this.SendPropertyChanged("payment_id");
					this.Onpayment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipping_id", DbType="Int")]
		public System.Nullable<int> shipping_id
		{
			get
			{
				return this._shipping_id;
			}
			set
			{
				if ((this._shipping_id != value))
				{
					if (this._tb_shipping.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onshipping_idChanging(value);
					this.SendPropertyChanging();
					this._shipping_id = value;
					this.SendPropertyChanged("shipping_id");
					this.Onshipping_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_order_tb_order_detail", Storage="_tb_order_details", ThisKey="order_id", OtherKey="order_id")]
		public EntitySet<tb_order_detail> tb_order_details
		{
			get
			{
				return this._tb_order_details;
			}
			set
			{
				this._tb_order_details.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_payment_tb_order", Storage="_tb_payment", ThisKey="payment_id", OtherKey="payment_id", IsForeignKey=true)]
		public tb_payment tb_payment
		{
			get
			{
				return this._tb_payment.Entity;
			}
			set
			{
				tb_payment previousValue = this._tb_payment.Entity;
				if (((previousValue != value) 
							|| (this._tb_payment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_payment.Entity = null;
						previousValue.tb_orders.Remove(this);
					}
					this._tb_payment.Entity = value;
					if ((value != null))
					{
						value.tb_orders.Add(this);
						this._payment_id = value.payment_id;
					}
					else
					{
						this._payment_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_payment");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_order", Storage="_tb_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public tb_user tb_user
		{
			get
			{
				return this._tb_user.Entity;
			}
			set
			{
				tb_user previousValue = this._tb_user.Entity;
				if (((previousValue != value) 
							|| (this._tb_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_user.Entity = null;
						previousValue.tb_orders.Remove(this);
					}
					this._tb_user.Entity = value;
					if ((value != null))
					{
						value.tb_orders.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_shipping_tb_order", Storage="_tb_shipping", ThisKey="shipping_id", OtherKey="shipping_id", IsForeignKey=true)]
		public tb_shipping tb_shipping
		{
			get
			{
				return this._tb_shipping.Entity;
			}
			set
			{
				tb_shipping previousValue = this._tb_shipping.Entity;
				if (((previousValue != value) 
							|| (this._tb_shipping.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_shipping.Entity = null;
						previousValue.tb_orders.Remove(this);
					}
					this._tb_shipping.Entity = value;
					if ((value != null))
					{
						value.tb_orders.Add(this);
						this._shipping_id = value.shipping_id;
					}
					else
					{
						this._shipping_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_shipping");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_order_details(tb_order_detail entity)
		{
			this.SendPropertyChanging();
			entity.tb_order = this;
		}
		
		private void detach_tb_order_details(tb_order_detail entity)
		{
			this.SendPropertyChanging();
			entity.tb_order = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_cart_item")]
	public partial class tb_cart_item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cartitem_id;
		
		private System.Nullable<int> _cart_id;
		
		private System.Nullable<int> _product_id;
		
		private System.Nullable<int> _quantity;
		
		private EntityRef<tb_product> _tb_product;
		
		private EntityRef<tb_cart> _tb_cart;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncartitem_idChanging(int value);
    partial void Oncartitem_idChanged();
    partial void Oncart_idChanging(System.Nullable<int> value);
    partial void Oncart_idChanged();
    partial void Onproduct_idChanging(System.Nullable<int> value);
    partial void Onproduct_idChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    #endregion
		
		public tb_cart_item()
		{
			this._tb_product = default(EntityRef<tb_product>);
			this._tb_cart = default(EntityRef<tb_cart>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cartitem_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cartitem_id
		{
			get
			{
				return this._cartitem_id;
			}
			set
			{
				if ((this._cartitem_id != value))
				{
					this.Oncartitem_idChanging(value);
					this.SendPropertyChanging();
					this._cartitem_id = value;
					this.SendPropertyChanged("cartitem_id");
					this.Oncartitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cart_id", DbType="Int")]
		public System.Nullable<int> cart_id
		{
			get
			{
				return this._cart_id;
			}
			set
			{
				if ((this._cart_id != value))
				{
					if (this._tb_cart.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncart_idChanging(value);
					this.SendPropertyChanging();
					this._cart_id = value;
					this.SendPropertyChanged("cart_id");
					this.Oncart_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int")]
		public System.Nullable<int> product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._tb_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_cart_item", Storage="_tb_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
		public tb_product tb_product
		{
			get
			{
				return this._tb_product.Entity;
			}
			set
			{
				tb_product previousValue = this._tb_product.Entity;
				if (((previousValue != value) 
							|| (this._tb_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_product.Entity = null;
						previousValue.tb_cart_items.Remove(this);
					}
					this._tb_product.Entity = value;
					if ((value != null))
					{
						value.tb_cart_items.Add(this);
						this._product_id = value.product_id;
					}
					else
					{
						this._product_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_product");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cart_tb_cart_item", Storage="_tb_cart", ThisKey="cart_id", OtherKey="cart_id", IsForeignKey=true)]
		public tb_cart tb_cart
		{
			get
			{
				return this._tb_cart.Entity;
			}
			set
			{
				tb_cart previousValue = this._tb_cart.Entity;
				if (((previousValue != value) 
							|| (this._tb_cart.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_cart.Entity = null;
						previousValue.tb_cart_items.Remove(this);
					}
					this._tb_cart.Entity = value;
					if ((value != null))
					{
						value.tb_cart_items.Add(this);
						this._cart_id = value.cart_id;
					}
					else
					{
						this._cart_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_cart");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_cart")]
	public partial class tb_cart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cart_id;
		
		private System.Nullable<int> _user_id;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private EntitySet<tb_cart_item> _tb_cart_items;
		
		private EntityRef<tb_user> _tb_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncart_idChanging(int value);
    partial void Oncart_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    #endregion
		
		public tb_cart()
		{
			this._tb_cart_items = new EntitySet<tb_cart_item>(new Action<tb_cart_item>(this.attach_tb_cart_items), new Action<tb_cart_item>(this.detach_tb_cart_items));
			this._tb_user = default(EntityRef<tb_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cart_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cart_id
		{
			get
			{
				return this._cart_id;
			}
			set
			{
				if ((this._cart_id != value))
				{
					this.Oncart_idChanging(value);
					this.SendPropertyChanging();
					this._cart_id = value;
					this.SendPropertyChanged("cart_id");
					this.Oncart_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._tb_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cart_tb_cart_item", Storage="_tb_cart_items", ThisKey="cart_id", OtherKey="cart_id")]
		public EntitySet<tb_cart_item> tb_cart_items
		{
			get
			{
				return this._tb_cart_items;
			}
			set
			{
				this._tb_cart_items.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_cart", Storage="_tb_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public tb_user tb_user
		{
			get
			{
				return this._tb_user.Entity;
			}
			set
			{
				tb_user previousValue = this._tb_user.Entity;
				if (((previousValue != value) 
							|| (this._tb_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_user.Entity = null;
						previousValue.tb_carts.Remove(this);
					}
					this._tb_user.Entity = value;
					if ((value != null))
					{
						value.tb_carts.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_cart_items(tb_cart_item entity)
		{
			this.SendPropertyChanging();
			entity.tb_cart = this;
		}
		
		private void detach_tb_cart_items(tb_cart_item entity)
		{
			this.SendPropertyChanging();
			entity.tb_cart = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_brand")]
	public partial class tb_brand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _brand_id;
		
		private string _name;
		
		private string _description;
		
		private EntitySet<tb_product> _tb_products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbrand_idChanging(int value);
    partial void Onbrand_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public tb_brand()
		{
			this._tb_products = new EntitySet<tb_product>(new Action<tb_product>(this.attach_tb_products), new Action<tb_product>(this.detach_tb_products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int brand_id
		{
			get
			{
				return this._brand_id;
			}
			set
			{
				if ((this._brand_id != value))
				{
					this.Onbrand_idChanging(value);
					this.SendPropertyChanging();
					this._brand_id = value;
					this.SendPropertyChanged("brand_id");
					this.Onbrand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_brand_tb_product", Storage="_tb_products", ThisKey="brand_id", OtherKey="brand_id")]
		public EntitySet<tb_product> tb_products
		{
			get
			{
				return this._tb_products;
			}
			set
			{
				this._tb_products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_products(tb_product entity)
		{
			this.SendPropertyChanging();
			entity.tb_brand = this;
		}
		
		private void detach_tb_products(tb_product entity)
		{
			this.SendPropertyChanging();
			entity.tb_brand = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_user")]
	public partial class tb_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _password;
		
		private string _full_name;
		
		private string _email;
		
		private string _phone;
		
		private System.Nullable<bool> _usertype;
		
		private string _address;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private EntitySet<tb_order> _tb_orders;
		
		private EntitySet<tb_cart> _tb_carts;
		
		private EntitySet<tb_review> _tb_reviews;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnusertypeChanging(System.Nullable<bool> value);
    partial void OnusertypeChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    #endregion
		
		public tb_user()
		{
			this._tb_orders = new EntitySet<tb_order>(new Action<tb_order>(this.attach_tb_orders), new Action<tb_order>(this.detach_tb_orders));
			this._tb_carts = new EntitySet<tb_cart>(new Action<tb_cart>(this.attach_tb_carts), new Action<tb_cart>(this.detach_tb_carts));
			this._tb_reviews = new EntitySet<tb_review>(new Action<tb_review>(this.attach_tb_reviews), new Action<tb_review>(this.detach_tb_reviews));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(100)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="NVarChar(100)")]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this.Onfull_nameChanging(value);
					this.SendPropertyChanging();
					this._full_name = value;
					this.SendPropertyChanged("full_name");
					this.Onfull_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="Bit")]
		public System.Nullable<bool> usertype
		{
			get
			{
				return this._usertype;
			}
			set
			{
				if ((this._usertype != value))
				{
					this.OnusertypeChanging(value);
					this.SendPropertyChanging();
					this._usertype = value;
					this.SendPropertyChanged("usertype");
					this.OnusertypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_order", Storage="_tb_orders", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<tb_order> tb_orders
		{
			get
			{
				return this._tb_orders;
			}
			set
			{
				this._tb_orders.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_cart", Storage="_tb_carts", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<tb_cart> tb_carts
		{
			get
			{
				return this._tb_carts;
			}
			set
			{
				this._tb_carts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_review", Storage="_tb_reviews", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<tb_review> tb_reviews
		{
			get
			{
				return this._tb_reviews;
			}
			set
			{
				this._tb_reviews.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_orders(tb_order entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = this;
		}
		
		private void detach_tb_orders(tb_order entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = null;
		}
		
		private void attach_tb_carts(tb_cart entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = this;
		}
		
		private void detach_tb_carts(tb_cart entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = null;
		}
		
		private void attach_tb_reviews(tb_review entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = this;
		}
		
		private void detach_tb_reviews(tb_review entity)
		{
			this.SendPropertyChanging();
			entity.tb_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_shipping")]
	public partial class tb_shipping : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _shipping_id;
		
		private string _address;
		
		private string _city;
		
		private string _postal_code;
		
		private string _shipping_method;
		
		private string _tracking_number;
		
		private EntitySet<tb_order> _tb_orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onshipping_idChanging(int value);
    partial void Onshipping_idChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void Onpostal_codeChanging(string value);
    partial void Onpostal_codeChanged();
    partial void Onshipping_methodChanging(string value);
    partial void Onshipping_methodChanged();
    partial void Ontracking_numberChanging(string value);
    partial void Ontracking_numberChanged();
    #endregion
		
		public tb_shipping()
		{
			this._tb_orders = new EntitySet<tb_order>(new Action<tb_order>(this.attach_tb_orders), new Action<tb_order>(this.detach_tb_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipping_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int shipping_id
		{
			get
			{
				return this._shipping_id;
			}
			set
			{
				if ((this._shipping_id != value))
				{
					this.Onshipping_idChanging(value);
					this.SendPropertyChanging();
					this._shipping_id = value;
					this.SendPropertyChanged("shipping_id");
					this.Onshipping_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="NVarChar(50)")]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this.Onpostal_codeChanging(value);
					this.SendPropertyChanging();
					this._postal_code = value;
					this.SendPropertyChanged("postal_code");
					this.Onpostal_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shipping_method", DbType="NVarChar(50)")]
		public string shipping_method
		{
			get
			{
				return this._shipping_method;
			}
			set
			{
				if ((this._shipping_method != value))
				{
					this.Onshipping_methodChanging(value);
					this.SendPropertyChanging();
					this._shipping_method = value;
					this.SendPropertyChanged("shipping_method");
					this.Onshipping_methodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tracking_number", DbType="NVarChar(50)")]
		public string tracking_number
		{
			get
			{
				return this._tracking_number;
			}
			set
			{
				if ((this._tracking_number != value))
				{
					this.Ontracking_numberChanging(value);
					this.SendPropertyChanging();
					this._tracking_number = value;
					this.SendPropertyChanged("tracking_number");
					this.Ontracking_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_shipping_tb_order", Storage="_tb_orders", ThisKey="shipping_id", OtherKey="shipping_id")]
		public EntitySet<tb_order> tb_orders
		{
			get
			{
				return this._tb_orders;
			}
			set
			{
				this._tb_orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_orders(tb_order entity)
		{
			this.SendPropertyChanging();
			entity.tb_shipping = this;
		}
		
		private void detach_tb_orders(tb_order entity)
		{
			this.SendPropertyChanging();
			entity.tb_shipping = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_review")]
	public partial class tb_review : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _review_id;
		
		private System.Nullable<int> _user_id;
		
		private System.Nullable<int> _product_id;
		
		private string _comment;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private EntityRef<tb_product> _tb_product;
		
		private EntityRef<tb_user> _tb_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreview_idChanging(int value);
    partial void Onreview_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onproduct_idChanging(System.Nullable<int> value);
    partial void Onproduct_idChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    #endregion
		
		public tb_review()
		{
			this._tb_product = default(EntityRef<tb_product>);
			this._tb_user = default(EntityRef<tb_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_review_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int review_id
		{
			get
			{
				return this._review_id;
			}
			set
			{
				if ((this._review_id != value))
				{
					this.Onreview_idChanging(value);
					this.SendPropertyChanging();
					this._review_id = value;
					this.SendPropertyChanged("review_id");
					this.Onreview_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._tb_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int")]
		public System.Nullable<int> product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._tb_product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_product_tb_review", Storage="_tb_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
		public tb_product tb_product
		{
			get
			{
				return this._tb_product.Entity;
			}
			set
			{
				tb_product previousValue = this._tb_product.Entity;
				if (((previousValue != value) 
							|| (this._tb_product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_product.Entity = null;
						previousValue.tb_reviews.Remove(this);
					}
					this._tb_product.Entity = value;
					if ((value != null))
					{
						value.tb_reviews.Add(this);
						this._product_id = value.product_id;
					}
					else
					{
						this._product_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_product");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_user_tb_review", Storage="_tb_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public tb_user tb_user
		{
			get
			{
				return this._tb_user.Entity;
			}
			set
			{
				tb_user previousValue = this._tb_user.Entity;
				if (((previousValue != value) 
							|| (this._tb_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_user.Entity = null;
						previousValue.tb_reviews.Remove(this);
					}
					this._tb_user.Entity = value;
					if ((value != null))
					{
						value.tb_reviews.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
